spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      host: localhost
      port: 27017
      database: test
      username: ""
      password: ""
  application:
    name: server_2
  cloud:
    nacos:
      #      config:
      #        # 配置中心服务地址
      #        server-addr: 127.0.0.1:8848
      #        # 指定后缀名
      #        file-extension: yml
      #        # 指定命名空间
      #        namespace: e3d505d8-b5de-420c-ae71-795f14e3ec14
      #        # 指定所属分组
      #        group: send
      #        # 拓展分组
      #        extension-configs:
      #          # 拓展数据源相关配置，其中data-id为nacos中配置的Data ID，为dev分组，开启热更新
      #          - dataId: database.yml
      #            group: dev
      #            refresh: true
      #          # 拓展nacos相关配置，其中data-id为nacos中配置的Data ID，为dev分组，开启热更新
      #          - dataId: nacos.yml
      #            group: dev
      #            refresh: true
      #          # 拓展其他相关配置，其中data-id为nacos中配置的Data ID，为dev分组，开启热更新
      #          - dataId: other.yml
      #            group: dev
      #            refresh: true

      discovery:
        server-addr: 127.0.0.1:8848
        namespace: LargeMedicalServicePlatform
      username: nacos
      password: nacos
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot
    username: root
    password: 123456


#mybatis:
#  mapper-locations: classpath:Dao/*.xml
mybatis-plus:
  mapper-locations: classpath:Dao/*.xml
  type-aliases-package: com.example.RealClass.User,com.example.RealClass.Docter
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8081
#  servlet:
#    context-path: /websocket